#!/usr/bin/env bash
# instalar dependencias (futuramente o ruby)
apt install tar clang -y

# atualizar
git pull

# o tar preserva as premissões e extrai como a função "extrair aquivos"
tar -xzvf backup.tar.gz

# usa o wildlist para instalar
echo "instalando"
./wildlist -r reinstall
echo "concluido"
